name: timed_app
description: "A new Flutter project."
publish_to: "C:/Users/dev/Documents/projects/flutter/timed_app/releases"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  audioplayers: ^6.1.0
  equatable: ^2.0.7
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  hexcolor: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  logger: ^2.6.1
  path: ^1.9.1
  path_provider: ^2.1.5
  uuid: ^4.5.1
  window_manager: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  msix: ^3.16.12

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# flutter_launcher_icons:
#   android: false
#   ios: false
#   windows:
#     generate: true
#     image_path: "assets/images/disc.png"
#     icon_size: 48 # min:48, max:256, default: 48
#   macos:
#     generate: true
#     image_path: "assets/images/disc.png"
#     icon_size: 48
# msix_config:
#   display_name: Timed Player
#   identity_name: com.timedplayer.timedplayer
#   publisher_display_name: Timed Player - (Lazarus Muya)
#   publisher: CN=TIMED-PLAYER-2025-V1
#   msix_version: 1.0.0.0
#   logo_path: assets/images/disc.png
